import { AtonType } from "../declarations/dtos/dtos"

type AtonData = {
  ts: string
  lcl_ts: string
  pkgType: string
  pkgId: number
  pkgCh: string
  msgType: number
  msgTypeDesc: string
  repeat: number
  seqno: number
  dest_mmsi: number
  retransmit: number
  dac: number
  fid: number
  volt_int: number
  volt_ex1: number
  volt_ex2: number
  off_pos: number
  ambient: number
  racon: number
  light: number
  health: number
  beat: number
  alarm_on: number
  buoy_led_power: number
  buoy_low_vin: number
  buoy_photocell: number
  buoy_temp: number
  buoy_force_off: number
  buoy_islight: number
  buoy_errled_short: number
  buoy_errled_open: number
  buoy_errled_voltlow: number
  buoy_errled_vinlow: number
  buoy_errled_power: number
  buoy_adjmaxpower: number
  buoy_sensor_interrupt: number
  buoy_solarcharging: number
  aa_rowcountby_mmsi: number
  ss_ts: string
  ss_pkgType: string
  ss_pkgId: number
  ss_pkgCh: string
  ss_msgType: number
  ss_msgTypeDesc: string
  ss_repeat: number
  ss_aidType: number
  ss_aidTypeDesc: string
  ss_aidName: string
  ss_positionAccuracy: number
  ss_positionAccuracyDesc: string
  ss_longitude: number
  ss_latitude: number
  ss_to_bow: number
  ss_to_stern: number
  ss_to_port: number
  ss_to_starboard: number
  ss_epfd: number
  ss_epfdDesc: string
  ss_utc_second: number
  ss_off_position: number
  ss_regional: number
  ss_raimFlag: number
  ss_virtualAid: number
  ss_assigned: number
  ss_rowcountby_mmsi: number
  al_region: string
  region: string
  status: number
}

export type Aton = {
  mmsi: number
  type: AtonType
  name: string
  al_mmsi?: number
  al_type?: string
  al_name?: string
  data: AtonData[]
}

export const allAtonData: Aton[] = [
  {
    mmsi: 995331257,
    type: 'Buoy',
    name: 'John XYZ',
    data: [
      { ts: "2024-08-20 04:35:47", lcl_ts: "2024-08-20 12:35:47", pkgType: "!ABVDM", pkgId: 6, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 13.95, volt_ex1: 13.5, volt_ex2: 42.0, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 0, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:05", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "A", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.55465666666667, ss_latitude: 1.3145066666666667, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 4, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:36:47", lcl_ts: "2024-08-20 12:36:47", pkgType: "!ABVDM", pkgId: 6, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 13.95, volt_ex1: 13.5, volt_ex2: 42.0, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 0, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:05", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "A", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.55465666666667, ss_latitude: 1.3145066666666667, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 4, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:37:47", lcl_ts: "2024-08-20 12:37:47", pkgType: "!ABVDM", pkgId: 6, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 13.95, volt_ex1: 13.5, volt_ex2: 42.0, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 0, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:05", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "A", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.55465666666667, ss_latitude: 1.3145066666666667, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 4, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:38:47", lcl_ts: "2024-08-20 12:38:47", pkgType: "!ABVDM", pkgId: 6, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 13.95, volt_ex1: 13.5, volt_ex2: 42.0, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 0, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:05", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "A", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.55465666666667, ss_latitude: 1.3145066666666667, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 4, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:39:47", lcl_ts: "2024-08-20 12:39:47", pkgType: "!ABVDM", pkgId: 6, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 13.95, volt_ex1: 13.5, volt_ex2: 42.0, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 0, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:05", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "A", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.55465666666667, ss_latitude: 1.3145066666666667, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 4, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:40:47", lcl_ts: "2024-08-20 12:40:47", pkgType: "!ABVDM", pkgId: 6, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 13.95, volt_ex1: 13.5, volt_ex2: 42.0, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 0, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:05", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "A", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.55465666666667, ss_latitude: 1.3145066666666667, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 4, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
    ]
  },
  {
    mmsi: 995331256,
    type: 'Beacon',
    name: 'PTP TSY',
    data: [
      { ts: "2024-08-20 04:35:23", lcl_ts: "2024-08-20 12:35:23", pkgType: "!ABVDM", pkgId: 1, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 14.5, volt_ex1: 13.3, volt_ex2: 41.6, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:23", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "B", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.95918, ss_latitude: 1.31392, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 22, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:36:23", lcl_ts: "2024-08-20 12:36:23", pkgType: "!ABVDM", pkgId: 1, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 14.5, volt_ex1: 13.3, volt_ex2: 41.6, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:23", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "B", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.95918, ss_latitude: 1.31392, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 22, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:37:23", lcl_ts: "2024-08-20 12:37:23", pkgType: "!ABVDM", pkgId: 1, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 14.5, volt_ex1: 13.3, volt_ex2: 41.6, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:23", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "B", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.95918, ss_latitude: 1.31392, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 22, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:38:23", lcl_ts: "2024-08-20 12:38:23", pkgType: "!ABVDM", pkgId: 1, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 14.5, volt_ex1: 13.3, volt_ex2: 41.6, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:23", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "B", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.95918, ss_latitude: 1.31392, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 22, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
      { ts: "2024-08-20 04:39:23", lcl_ts: "2024-08-20 12:39:23", pkgType: "!ABVDM", pkgId: 1, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 1, dest_mmsi: 701, retransmit: 0, dac: 533, fid: 4, volt_int: 14.5, volt_ex1: 13.3, volt_ex2: 41.6, off_pos: 0, ambient: 3, racon: 0, light: 2, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 0, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 1, ss_ts: "2024-08-20 04:36:23", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "B", ss_msgType: 21, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "N/A", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.95918, ss_latitude: 1.31392, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 22, ss_off_position: 0, ss_regional: 228, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 1, al_region: "Wilayah Selatan", region: "Wilayah Selatan", status: 1 },
    ]
  },
  {
    mmsi: 995331258,
    type: 'Buoy',
    name: 'Signal 1',
    data: [
      { ts: "2024-08-21 04:00:00", lcl_ts: "2024-08-21 12:00:00", pkgType: "!ABVDM", pkgId: 1, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 2, dest_mmsi: 702, retransmit: 0, dac: 534, fid: 5, volt_int: 14.0, volt_ex1: 13.0, volt_ex2: 40.0, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:01:00", ss_pkgType: "!ABVDM", ss_pkgId: 2, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 1", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 110.56000, ss_latitude: 1.31500, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 229, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region A", region: "Region A", status: 1 },
      { ts: "2024-08-21 04:01:00", lcl_ts: "2024-08-21 12:01:00", pkgType: "!ABVDM", pkgId: 1, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 2, dest_mmsi: 702, retransmit: 0, dac: 534, fid: 5, volt_int: 14.0, volt_ex1: 13.0, volt_ex2: 40.0, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:01:00", ss_pkgType: "!ABVDM", ss_pkgId: 2, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 1", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 110.56000, ss_latitude: 1.31500, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 229, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region A", region: "Region A", status: 1 },
      { ts: "2024-08-21 04:02:00", lcl_ts: "2024-08-21 12:02:00", pkgType: "!ABVDM", pkgId: 1, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 2, dest_mmsi: 702, retransmit: 0, dac: 534, fid: 5, volt_int: 14.0, volt_ex1: 13.0, volt_ex2: 40.0, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:01:00", ss_pkgType: "!ABVDM", ss_pkgId: 2, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 1", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 110.56000, ss_latitude: 1.31500, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 229, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region A", region: "Region A", status: 1 },
      { ts: "2024-08-21 04:03:00", lcl_ts: "2024-08-21 12:03:00", pkgType: "!ABVDM", pkgId: 1, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 2, dest_mmsi: 702, retransmit: 0, dac: 534, fid: 5, volt_int: 14.0, volt_ex1: 13.0, volt_ex2: 40.0, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:01:00", ss_pkgType: "!ABVDM", ss_pkgId: 2, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 1", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 110.56000, ss_latitude: 1.31500, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 229, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region A", region: "Region A", status: 1 },
      { ts: "2024-08-21 04:04:00", lcl_ts: "2024-08-21 12:04:00", pkgType: "!ABVDM", pkgId: 1, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 2, dest_mmsi: 702, retransmit: 0, dac: 534, fid: 5, volt_int: 14.0, volt_ex1: 13.0, volt_ex2: 40.0, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 1, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:01:00", ss_pkgType: "!ABVDM", ss_pkgId: 2, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 1", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 110.56000, ss_latitude: 1.31500, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 229, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region A", region: "Region A", status: 1 },
    ]
  },
  {
    mmsi: 995331259,
    type: 'Beacon',
    name: 'Signal 2',
    data: [
      { ts: "2024-08-21 04:05:00", lcl_ts: "2024-08-21 12:05:00", pkgType: "!ABVDM", pkgId: 2, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 3, dest_mmsi: 703, retransmit: 1, dac: 535, fid: 6, volt_int: 14.2, volt_ex1: 13.4, volt_ex2: 41.2, off_pos: 1, ambient: 5, racon: 1, light: 2, health: 0, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:06:00", ss_pkgType: "!ABVDM", ss_pkgId: 3, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 2", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.56500, ss_latitude: 1.31600, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 230, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region B", region: "Region B", status: 1 },
      { ts: "2024-08-21 04:06:00", lcl_ts: "2024-08-21 12:06:00", pkgType: "!ABVDM", pkgId: 2, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 3, dest_mmsi: 703, retransmit: 1, dac: 535, fid: 6, volt_int: 14.2, volt_ex1: 13.4, volt_ex2: 41.2, off_pos: 1, ambient: 5, racon: 1, light: 2, health: 0, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:06:00", ss_pkgType: "!ABVDM", ss_pkgId: 3, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 2", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.56500, ss_latitude: 1.31600, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 230, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region B", region: "Region B", status: 1 },
      { ts: "2024-08-21 04:07:00", lcl_ts: "2024-08-21 12:07:00", pkgType: "!ABVDM", pkgId: 2, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 3, dest_mmsi: 703, retransmit: 1, dac: 535, fid: 6, volt_int: 14.2, volt_ex1: 13.4, volt_ex2: 41.2, off_pos: 1, ambient: 5, racon: 1, light: 2, health: 0, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:06:00", ss_pkgType: "!ABVDM", ss_pkgId: 3, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 2", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.56500, ss_latitude: 1.31600, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 230, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region B", region: "Region B", status: 1 },
      { ts: "2024-08-21 04:08:00", lcl_ts: "2024-08-21 12:08:00", pkgType: "!ABVDM", pkgId: 2, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 3, dest_mmsi: 703, retransmit: 1, dac: 535, fid: 6, volt_int: 14.2, volt_ex1: 13.4, volt_ex2: 41.2, off_pos: 1, ambient: 5, racon: 1, light: 2, health: 0, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:06:00", ss_pkgType: "!ABVDM", ss_pkgId: 3, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 2", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.56500, ss_latitude: 1.31600, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 230, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region B", region: "Region B", status: 1 },
      { ts: "2024-08-21 04:09:00", lcl_ts: "2024-08-21 12:09:00", pkgType: "!ABVDM", pkgId: 2, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 3, dest_mmsi: 703, retransmit: 1, dac: 535, fid: 6, volt_int: 14.2, volt_ex1: 13.4, volt_ex2: 41.2, off_pos: 1, ambient: 5, racon: 1, light: 2, health: 0, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:06:00", ss_pkgType: "!ABVDM", ss_pkgId: 3, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 2", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.56500, ss_latitude: 1.31600, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 230, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region B", region: "Region B", status: 1 },
    ]
  },
  {
    mmsi: 995331260,
    type: 'Buoy',
    name: 'Signal 3',
    data: [
      { ts: "2024-08-21 04:10:00", lcl_ts: "2024-08-21 12:10:00", pkgType: "!ABVDM", pkgId: 3, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 4, dest_mmsi: 704, retransmit: 0, dac: 536, fid: 7, volt_int: 14.1, volt_ex1: 13.2, volt_ex2: 40.8, off_pos: 0, ambient: 3, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:11:00", ss_pkgType: "!ABVDM", ss_pkgId: 4, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 3", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.57000, ss_latitude: 1.31700, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 20, ss_off_position: 0, ss_regional: 231, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region C", region: "Region C", status: 1 },
      { ts: "2024-08-21 04:11:00", lcl_ts: "2024-08-21 12:11:00", pkgType: "!ABVDM", pkgId: 3, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 4, dest_mmsi: 704, retransmit: 0, dac: 536, fid: 7, volt_int: 14.1, volt_ex1: 13.2, volt_ex2: 40.8, off_pos: 0, ambient: 3, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:11:00", ss_pkgType: "!ABVDM", ss_pkgId: 4, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 3", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.57000, ss_latitude: 1.31700, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 20, ss_off_position: 0, ss_regional: 231, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region C", region: "Region C", status: 1 },
      { ts: "2024-08-21 04:12:00", lcl_ts: "2024-08-21 12:12:00", pkgType: "!ABVDM", pkgId: 3, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 4, dest_mmsi: 704, retransmit: 0, dac: 536, fid: 7, volt_int: 14.1, volt_ex1: 13.2, volt_ex2: 40.8, off_pos: 0, ambient: 3, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:11:00", ss_pkgType: "!ABVDM", ss_pkgId: 4, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 3", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.57000, ss_latitude: 1.31700, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 20, ss_off_position: 0, ss_regional: 231, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region C", region: "Region C", status: 1 },
      { ts: "2024-08-21 04:13:00", lcl_ts: "2024-08-21 12:13:00", pkgType: "!ABVDM", pkgId: 3, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 4, dest_mmsi: 704, retransmit: 0, dac: 536, fid: 7, volt_int: 14.1, volt_ex1: 13.2, volt_ex2: 40.8, off_pos: 0, ambient: 3, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:11:00", ss_pkgType: "!ABVDM", ss_pkgId: 4, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 3", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.57000, ss_latitude: 1.31700, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 20, ss_off_position: 0, ss_regional: 231, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region C", region: "Region C", status: 1 },
      { ts: "2024-08-21 04:14:00", lcl_ts: "2024-08-21 12:14:00", pkgType: "!ABVDM", pkgId: 3, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 4, dest_mmsi: 704, retransmit: 0, dac: 536, fid: 7, volt_int: 14.1, volt_ex1: 13.2, volt_ex2: 40.8, off_pos: 0, ambient: 3, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:11:00", ss_pkgType: "!ABVDM", ss_pkgId: 4, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 3", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.57000, ss_latitude: 1.31700, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 20, ss_off_position: 0, ss_regional: 231, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region C", region: "Region C", status: 1 },
    ]
  },
  {
    mmsi: 995331261,
    type: 'Beacon',
    name: 'Signal 4',
    data: [
      { ts: "2024-08-21 04:15:00", lcl_ts: "2024-08-21 12:15:00", pkgType: "!ABVDM", pkgId: 4, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 5, dest_mmsi: 705, retransmit: 1, dac: 537, fid: 8, volt_int: 14.4, volt_ex1: 13.5, volt_ex2: 41.0, off_pos: 0, ambient: 6, racon: 1, light: 2, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:16:00", ss_pkgType: "!ABVDM", ss_pkgId: 5, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 4", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.57500, ss_latitude: 1.31800, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 25, ss_off_position: 0, ss_regional: 232, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region D", region: "Region D", status: 1 },
      { ts: "2024-08-21 04:16:00", lcl_ts: "2024-08-21 12:16:00", pkgType: "!ABVDM", pkgId: 4, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 5, dest_mmsi: 705, retransmit: 1, dac: 537, fid: 8, volt_int: 14.4, volt_ex1: 13.5, volt_ex2: 41.0, off_pos: 0, ambient: 6, racon: 1, light: 2, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:16:00", ss_pkgType: "!ABVDM", ss_pkgId: 5, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 4", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.57500, ss_latitude: 1.31800, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 25, ss_off_position: 0, ss_regional: 232, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region D", region: "Region D", status: 1 },
      { ts: "2024-08-21 04:17:00", lcl_ts: "2024-08-21 12:17:00", pkgType: "!ABVDM", pkgId: 4, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 5, dest_mmsi: 705, retransmit: 1, dac: 537, fid: 8, volt_int: 14.4, volt_ex1: 13.5, volt_ex2: 41.0, off_pos: 0, ambient: 6, racon: 1, light: 2, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:16:00", ss_pkgType: "!ABVDM", ss_pkgId: 5, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 4", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.57500, ss_latitude: 1.31800, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 25, ss_off_position: 0, ss_regional: 232, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region D", region: "Region D", status: 1 },
      { ts: "2024-08-21 04:18:00", lcl_ts: "2024-08-21 12:18:00", pkgType: "!ABVDM", pkgId: 4, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 5, dest_mmsi: 705, retransmit: 1, dac: 537, fid: 8, volt_int: 14.4, volt_ex1: 13.5, volt_ex2: 41.0, off_pos: 0, ambient: 6, racon: 1, light: 2, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 0, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:16:00", ss_pkgType: "!ABVDM", ss_pkgId: 5, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 4", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.57500, ss_latitude: 1.31800, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 25, ss_off_position: 0, ss_regional: 232, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region D", region: "Region D", status: 1 },
    ]
  },
  {
    mmsi: 995331262,
    type: 'Buoy',
    name: 'Signal 5',
    data: [
      { ts: "2024-08-21 04:20:00", lcl_ts: "2024-08-21 12:20:00", pkgType: "!ABVDM", pkgId: 5, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 6, dest_mmsi: 706, retransmit: 0, dac: 538, fid: 9, volt_int: 14.6, volt_ex1: 13.6, volt_ex2: 41.4, off_pos: 0, ambient: 5, racon: 0, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:21:00", ss_pkgType: "!ABVDM", ss_pkgId: 6, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 5", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.58000, ss_latitude: 1.31900, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 233, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region E", region: "Region E", status: 1 },
      { ts: "2024-08-21 04:21:00", lcl_ts: "2024-08-21 12:21:00", pkgType: "!ABVDM", pkgId: 5, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 6, dest_mmsi: 706, retransmit: 0, dac: 538, fid: 9, volt_int: 14.6, volt_ex1: 13.6, volt_ex2: 41.4, off_pos: 0, ambient: 5, racon: 0, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:21:00", ss_pkgType: "!ABVDM", ss_pkgId: 6, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 5", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.58000, ss_latitude: 1.31900, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 233, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region E", region: "Region E", status: 1 },
      { ts: "2024-08-21 04:22:00", lcl_ts: "2024-08-21 12:22:00", pkgType: "!ABVDM", pkgId: 5, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 6, dest_mmsi: 706, retransmit: 0, dac: 538, fid: 9, volt_int: 14.6, volt_ex1: 13.6, volt_ex2: 41.4, off_pos: 0, ambient: 5, racon: 0, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:21:00", ss_pkgType: "!ABVDM", ss_pkgId: 6, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 5", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.58000, ss_latitude: 1.31900, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 233, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region E", region: "Region E", status: 1 },
      { ts: "2024-08-21 04:23:00", lcl_ts: "2024-08-21 12:23:00", pkgType: "!ABVDM", pkgId: 5, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 6, dest_mmsi: 706, retransmit: 0, dac: 538, fid: 9, volt_int: 14.6, volt_ex1: 13.6, volt_ex2: 41.4, off_pos: 0, ambient: 5, racon: 0, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:21:00", ss_pkgType: "!ABVDM", ss_pkgId: 6, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 5", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.58000, ss_latitude: 1.31900, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 233, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region E", region: "Region E", status: 1 },
      { ts: "2024-08-21 04:24:00", lcl_ts: "2024-08-21 12:24:00", pkgType: "!ABVDM", pkgId: 5, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 6, dest_mmsi: 706, retransmit: 0, dac: 538, fid: 9, volt_int: 14.6, volt_ex1: 13.6, volt_ex2: 41.4, off_pos: 0, ambient: 5, racon: 0, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 0, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:21:00", ss_pkgType: "!ABVDM", ss_pkgId: 6, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 5", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.58000, ss_latitude: 1.31900, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 233, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region E", region: "Region E", status: 1 },
    ]
  },
  {
    mmsi: 995331263,
    type: 'Beacon',
    name: 'Signal 6',
    data: [
      { ts: "2024-08-21 04:25:00", lcl_ts: "2024-08-21 12:25:00", pkgType: "!ABVDM", pkgId: 6, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 7, dest_mmsi: 707, retransmit: 1, dac: 539, fid: 10, volt_int: 14.8, volt_ex1: 13.7, volt_ex2: 41.5, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 0, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 0, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:26:00", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 6", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.58500, ss_latitude: 1.32000, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 234, ss_raimFlag: 1, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region F", region: "Region F", status: 1 },
      { ts: "2024-08-21 04:26:00", lcl_ts: "2024-08-21 12:26:00", pkgType: "!ABVDM", pkgId: 6, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 7, dest_mmsi: 707, retransmit: 1, dac: 539, fid: 10, volt_int: 14.8, volt_ex1: 13.7, volt_ex2: 41.5, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 0, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 0, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:26:00", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 6", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.58500, ss_latitude: 1.32000, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 234, ss_raimFlag: 1, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region F", region: "Region F", status: 1 },
      { ts: "2024-08-21 04:27:00", lcl_ts: "2024-08-21 12:27:00", pkgType: "!ABVDM", pkgId: 6, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 7, dest_mmsi: 707, retransmit: 1, dac: 539, fid: 10, volt_int: 14.8, volt_ex1: 13.7, volt_ex2: 41.5, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 0, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 0, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:26:00", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 6", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.58500, ss_latitude: 1.32000, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 234, ss_raimFlag: 1, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region F", region: "Region F", status: 1 },
      { ts: "2024-08-21 04:28:00", lcl_ts: "2024-08-21 12:28:00", pkgType: "!ABVDM", pkgId: 6, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 7, dest_mmsi: 707, retransmit: 1, dac: 539, fid: 10, volt_int: 14.8, volt_ex1: 13.7, volt_ex2: 41.5, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 0, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 0, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:26:00", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 6", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.58500, ss_latitude: 1.32000, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 234, ss_raimFlag: 1, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region F", region: "Region F", status: 1 },
      { ts: "2024-08-21 04:29:00", lcl_ts: "2024-08-21 12:29:00", pkgType: "!ABVDM", pkgId: 6, pkgCh: "B", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 7, dest_mmsi: 707, retransmit: 1, dac: 539, fid: 10, volt_int: 14.8, volt_ex1: 13.7, volt_ex2: 41.5, off_pos: 0, ambient: 4, racon: 1, light: 1, health: 1, beat: 0, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 0, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 0, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 1, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:26:00", ss_pkgType: "!ABVDM", ss_pkgId: 7, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 5, ss_aidTypeDesc: "Light without sectors", ss_aidName: "Signal 6", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.58500, ss_latitude: 1.32000, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 15, ss_off_position: 0, ss_regional: 234, ss_raimFlag: 1, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region F", region: "Region F", status: 1 },
    ]
  },
  {
    mmsi: 995331264,
    type: 'Buoy',
    name: 'Signal 7',
    data: [
      { ts: "2024-08-21 04:30:00", lcl_ts: "2024-08-21 12:30:00", pkgType: "!ABVDM", pkgId: 7, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 8, dest_mmsi: 708, retransmit: 0, dac: 540, fid: 11, volt_int: 15.0, volt_ex1: 13.8, volt_ex2: 41.6, off_pos: 0, ambient: 2, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 1, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:31:00", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 7", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.59000, ss_latitude: 1.32100, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 235, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region G", region: "Region G", status: 1 },
      { ts: "2024-08-21 04:31:00", lcl_ts: "2024-08-21 12:31:00", pkgType: "!ABVDM", pkgId: 7, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 8, dest_mmsi: 708, retransmit: 0, dac: 540, fid: 11, volt_int: 15.0, volt_ex1: 13.8, volt_ex2: 41.6, off_pos: 0, ambient: 2, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 1, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:31:00", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 7", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.59000, ss_latitude: 1.32100, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 235, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region G", region: "Region G", status: 1 },
      { ts: "2024-08-21 04:32:00", lcl_ts: "2024-08-21 12:32:00", pkgType: "!ABVDM", pkgId: 7, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 8, dest_mmsi: 708, retransmit: 0, dac: 540, fid: 11, volt_int: 15.0, volt_ex1: 13.8, volt_ex2: 41.6, off_pos: 0, ambient: 2, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 1, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:31:00", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 7", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.59000, ss_latitude: 1.32100, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 235, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region G", region: "Region G", status: 1 },
      { ts: "2024-08-21 04:33:00", lcl_ts: "2024-08-21 12:33:00", pkgType: "!ABVDM", pkgId: 7, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 8, dest_mmsi: 708, retransmit: 0, dac: 540, fid: 11, volt_int: 15.0, volt_ex1: 13.8, volt_ex2: 41.6, off_pos: 0, ambient: 2, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 1, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:31:00", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 7", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.59000, ss_latitude: 1.32100, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 235, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region G", region: "Region G", status: 1 },
      { ts: "2024-08-21 04:34:00", lcl_ts: "2024-08-21 12:34:00", pkgType: "!ABVDM", pkgId: 7, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 8, dest_mmsi: 708, retransmit: 0, dac: 540, fid: 11, volt_int: 15.0, volt_ex1: 13.8, volt_ex2: 41.6, off_pos: 0, ambient: 2, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 1, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:31:00", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 7", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.59000, ss_latitude: 1.32100, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 235, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region G", region: "Region G", status: 1 },
      { ts: "2024-08-21 04:35:00", lcl_ts: "2024-08-21 12:35:00", pkgType: "!ABVDM", pkgId: 7, pkgCh: "A", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 8, dest_mmsi: 708, retransmit: 0, dac: 540, fid: 11, volt_int: 15.0, volt_ex1: 13.8, volt_ex2: 41.6, off_pos: 0, ambient: 2, racon: 0, light: 1, health: 0, beat: 1, alarm_on: 1, buoy_led_power: 0, buoy_low_vin: 1, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 1, buoy_errled_open: 0, buoy_errled_voltlow: 1, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:31:00", ss_pkgType: "!ABVDM", ss_pkgId: 8, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 7, ss_aidTypeDesc: "Daymark", ss_aidName: "Signal 7", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.59000, ss_latitude: 1.32100, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 10, ss_off_position: 0, ss_regional: 235, ss_raimFlag: 1, ss_virtualAid: 1, ss_assigned: 1, ss_rowcountby_mmsi: 2, al_region: "Region G", region: "Region G", status: 1 },
    ]
  },
  {
    mmsi: 995331265,
    type: 'Beacon',
    name: 'Signal 8',
    data: [
      { ts: "2024-08-21 04:35:00", lcl_ts: "2024-08-21 12:35:00", pkgType: "!ABVDM", pkgId: 8, pkgCh: "A", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 9, dest_mmsi: 709, retransmit: 0, dac: 541, fid: 12, volt_int: 15.2, volt_ex1: 13.9, volt_ex2: 41.7, off_pos: 0, ambient: 6, racon: 0, light: 1, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 1, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:36:00", ss_pkgType: "!ABVDM", ss_pkgId: 9, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 8", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.59500, ss_latitude: 1.32200, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 30, ss_off_position: 0, ss_regional: 236, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region H", region: "Region H", status: 1 },
      { ts: "2024-08-21 04:36:00", lcl_ts: "2024-08-21 12:36:00", pkgType: "!ABVDM", pkgId: 8, pkgCh: "A", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 9, dest_mmsi: 709, retransmit: 0, dac: 541, fid: 12, volt_int: 15.2, volt_ex1: 13.9, volt_ex2: 41.7, off_pos: 0, ambient: 6, racon: 0, light: 1, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 1, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:36:00", ss_pkgType: "!ABVDM", ss_pkgId: 9, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 8", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.59500, ss_latitude: 1.32200, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 30, ss_off_position: 0, ss_regional: 236, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region H", region: "Region H", status: 1 },
      { ts: "2024-08-21 04:37:00", lcl_ts: "2024-08-21 12:37:00", pkgType: "!ABVDM", pkgId: 8, pkgCh: "A", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 9, dest_mmsi: 709, retransmit: 0, dac: 541, fid: 12, volt_int: 15.2, volt_ex1: 13.9, volt_ex2: 41.7, off_pos: 0, ambient: 6, racon: 0, light: 1, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 1, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:36:00", ss_pkgType: "!ABVDM", ss_pkgId: 9, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 8", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.59500, ss_latitude: 1.32200, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 30, ss_off_position: 0, ss_regional: 236, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region H", region: "Region H", status: 1 },
      { ts: "2024-08-21 04:38:00", lcl_ts: "2024-08-21 12:38:00", pkgType: "!ABVDM", pkgId: 8, pkgCh: "A", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 9, dest_mmsi: 709, retransmit: 0, dac: 541, fid: 12, volt_int: 15.2, volt_ex1: 13.9, volt_ex2: 41.7, off_pos: 0, ambient: 6, racon: 0, light: 1, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 1, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:36:00", ss_pkgType: "!ABVDM", ss_pkgId: 9, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 8", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.59500, ss_latitude: 1.32200, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 30, ss_off_position: 0, ss_regional: 236, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region H", region: "Region H", status: 1 },
      { ts: "2024-08-21 04:39:00", lcl_ts: "2024-08-21 12:39:00", pkgType: "!ABVDM", pkgId: 8, pkgCh: "A", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 9, dest_mmsi: 709, retransmit: 0, dac: 541, fid: 12, volt_int: 15.2, volt_ex1: 13.9, volt_ex2: 41.7, off_pos: 0, ambient: 6, racon: 0, light: 1, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 1, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:36:00", ss_pkgType: "!ABVDM", ss_pkgId: 9, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 8", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.59500, ss_latitude: 1.32200, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 30, ss_off_position: 0, ss_regional: 236, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region H", region: "Region H", status: 1 },
      { ts: "2024-08-21 04:40:00", lcl_ts: "2024-08-21 12:30:00", pkgType: "!ABVDM", pkgId: 8, pkgCh: "A", msgType: 7, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 9, dest_mmsi: 709, retransmit: 0, dac: 541, fid: 12, volt_int: 15.2, volt_ex1: 13.9, volt_ex2: 41.7, off_pos: 0, ambient: 6, racon: 0, light: 1, health: 1, beat: 0, alarm_on: 1, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 1, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 1, buoy_errled_voltlow: 0, buoy_errled_vinlow: 0, buoy_errled_power: 1, buoy_adjmaxpower: 1, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:36:00", ss_pkgType: "!ABVDM", ss_pkgId: 9, ss_pkgCh: "A", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 6, ss_aidTypeDesc: "Light with sectors", ss_aidName: "Signal 8", ss_positionAccuracy: 0, ss_positionAccuracyDesc: "an unaugmented GNSS fix with accuracy > 10m", ss_longitude: 106.59500, ss_latitude: 1.32200, ss_to_bow: 2, ss_to_stern: 2, ss_to_port: 2, ss_to_starboard: 2, ss_epfd: 1, ss_epfdDesc: "GPS", ss_utc_second: 30, ss_off_position: 0, ss_regional: 236, ss_raimFlag: 0, ss_virtualAid: 0, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region H", region: "Region H", status: 1 },
    ]
  },
  {
    mmsi: 995331266,
    type: 'Buoy',
    name: 'Signal 9',
    data: [
      { ts: "2024-08-21 04:40:00", lcl_ts: "2024-08-21 12:40:00", pkgType: "!ABVDM", pkgId: 9, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 10, dest_mmsi: 710, retransmit: 1, dac: 542, fid: 13, volt_int: 14.9, volt_ex1: 13.8, volt_ex2: 41.8, off_pos: 0, ambient: 5, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 1, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:41:00", ss_pkgType: "!ABVDM", ss_pkgId: 10, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 8, ss_aidTypeDesc: "Daymark with sector lights", ss_aidName: "Signal 9", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.60000, ss_latitude: 1.32300, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 5, ss_off_position: 0, ss_regional: 237, ss_raimFlag: 0, ss_virtualAid: 1, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region I", region: "Region I", status: 1 },
      { ts: "2024-08-21 04:41:00", lcl_ts: "2024-08-21 12:41:00", pkgType: "!ABVDM", pkgId: 9, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 10, dest_mmsi: 710, retransmit: 1, dac: 542, fid: 13, volt_int: 14.9, volt_ex1: 13.8, volt_ex2: 41.8, off_pos: 0, ambient: 5, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 1, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:41:00", ss_pkgType: "!ABVDM", ss_pkgId: 10, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 8, ss_aidTypeDesc: "Daymark with sector lights", ss_aidName: "Signal 9", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.60000, ss_latitude: 1.32300, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 5, ss_off_position: 0, ss_regional: 237, ss_raimFlag: 0, ss_virtualAid: 1, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region I", region: "Region I", status: 1 },
      { ts: "2024-08-21 04:42:00", lcl_ts: "2024-08-21 12:42:00", pkgType: "!ABVDM", pkgId: 9, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 10, dest_mmsi: 710, retransmit: 1, dac: 542, fid: 13, volt_int: 14.9, volt_ex1: 13.8, volt_ex2: 41.8, off_pos: 0, ambient: 5, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 1, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:41:00", ss_pkgType: "!ABVDM", ss_pkgId: 10, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 8, ss_aidTypeDesc: "Daymark with sector lights", ss_aidName: "Signal 9", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.60000, ss_latitude: 1.32300, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 5, ss_off_position: 0, ss_regional: 237, ss_raimFlag: 0, ss_virtualAid: 1, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region I", region: "Region I", status: 1 },
      { ts: "2024-08-21 04:43:00", lcl_ts: "2024-08-21 12:43:00", pkgType: "!ABVDM", pkgId: 9, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 10, dest_mmsi: 710, retransmit: 1, dac: 542, fid: 13, volt_int: 14.9, volt_ex1: 13.8, volt_ex2: 41.8, off_pos: 0, ambient: 5, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 1, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:41:00", ss_pkgType: "!ABVDM", ss_pkgId: 10, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 8, ss_aidTypeDesc: "Daymark with sector lights", ss_aidName: "Signal 9", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.60000, ss_latitude: 1.32300, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 5, ss_off_position: 0, ss_regional: 237, ss_raimFlag: 0, ss_virtualAid: 1, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region I", region: "Region I", status: 1 },
      { ts: "2024-08-21 04:44:00", lcl_ts: "2024-08-21 12:44:00", pkgType: "!ABVDM", pkgId: 9, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 10, dest_mmsi: 710, retransmit: 1, dac: 542, fid: 13, volt_int: 14.9, volt_ex1: 13.8, volt_ex2: 41.8, off_pos: 0, ambient: 5, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 1, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:41:00", ss_pkgType: "!ABVDM", ss_pkgId: 10, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 8, ss_aidTypeDesc: "Daymark with sector lights", ss_aidName: "Signal 9", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.60000, ss_latitude: 1.32300, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 5, ss_off_position: 0, ss_regional: 237, ss_raimFlag: 0, ss_virtualAid: 1, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region I", region: "Region I", status: 1 },
      { ts: "2024-08-21 04:45:00", lcl_ts: "2024-08-21 12:45:00", pkgType: "!ABVDM", pkgId: 9, pkgCh: "B", msgType: 6, msgTypeDesc: "Binary Addressed Message", repeat: 0, seqno: 10, dest_mmsi: 710, retransmit: 1, dac: 542, fid: 13, volt_int: 14.9, volt_ex1: 13.8, volt_ex2: 41.8, off_pos: 0, ambient: 5, racon: 1, light: 1, health: 1, beat: 1, alarm_on: 0, buoy_led_power: 1, buoy_low_vin: 0, buoy_photocell: 1, buoy_temp: 1, buoy_force_off: 0, buoy_islight: 1, buoy_errled_short: 0, buoy_errled_open: 0, buoy_errled_voltlow: 0, buoy_errled_vinlow: 1, buoy_errled_power: 1, buoy_adjmaxpower: 0, buoy_sensor_interrupt: 0, buoy_solarcharging: 1, aa_rowcountby_mmsi: 2, ss_ts: "2024-08-21 04:41:00", ss_pkgType: "!ABVDM", ss_pkgId: 10, ss_pkgCh: "B", ss_msgType: 22, ss_msgTypeDesc: "Aid to Navigation Report", ss_repeat: 0, ss_aidType: 8, ss_aidTypeDesc: "Daymark with sector lights", ss_aidName: "Signal 9", ss_positionAccuracy: 1, ss_positionAccuracyDesc: "an augmented GNSS fix with accuracy < 10m", ss_longitude: 106.60000, ss_latitude: 1.32300, ss_to_bow: 1, ss_to_stern: 1, ss_to_port: 1, ss_to_starboard: 1, ss_epfd: 2, ss_epfdDesc: "GLONASS", ss_utc_second: 5, ss_off_position: 0, ss_regional: 237, ss_raimFlag: 0, ss_virtualAid: 1, ss_assigned: 0, ss_rowcountby_mmsi: 2, al_region: "Region I", region: "Region I", status: 1 },
    ]
  }
]

function transformAtonArray(atonArray: Aton[]): AtonData[] {
  return atonArray.flatMap(aton =>
    aton.data.map(data => ({
      ...data,             // Spread all properties from AtonData inside data[]
      mmsi: aton.mmsi,     // Add or override properties from Aton
      type: aton.type,
      name: aton.name,
      al_mmsi: aton.al_mmsi,
      al_type: aton.al_type,
      al_name: aton.al_name
    }))
  );
}

console.log(transformAtonArray(allAtonData))